---
# This playbook provisions and deploys the application stack in a virtual machine.

- name: provision, configure and deploy example application
  hosts: all
  become: true
  tasks:
    - name: ensure necessary packages are present
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ present_packages }}"

    - name: copy nginx vhost configuration
      template:
        src: default.jd2
        dest: /etc/nginx/sites-available/default

    - name: set some php configurations
      lineinfile:
        dest: /etc/php5/fpm/php.ini
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^display_errors', line: 'display_errors = On' }
        - { regexp: '^display_startup_errors', line: 'display_startup_errors = On' }
        - { regexp: '^memory_limit', line: 'memory_limit = {{ php_memory_limit }}' }
      tags:
         - configuration

    - name: copy application index to target
      template:
        src: app.php.jd2
        dest: /var/www/index.php

    - name: copy application memory_leak to target
      template:
        src: memory_leak.php.jd2
        dest: /var/www/memory_leak.php

    - name: download composer
      get_url:
        url: https://getcomposer.org/installer
        dest: ~/installer

    - name: install composer
      command: "php ~/installer --install-dir=/usr/local/bin --filename=composer"

    - name: install memory-stat php library
      composer:
        command: require
        arguments: vega/memory-stat dev-master
        working_dir: /var/www

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart php5-fpm
      service:
        name: php5-fpm
        state: restarted